Numpy array and  basics

In [1]:
import numpy as np

Array creation

In [7]:
#1d array creation
arr_1d=np.array([10,20,30,40])
print(arr_1d,type(arr_1d))
#2d array
arr_2d=np.array([[10,20,30],[40,50,60]])
print(arr_2d,type(arr_1d))

[10 20 30 40] <class 'numpy.ndarray'>
[[10 20 30]
 [40 50 60]] <class 'numpy.ndarray'>


list vs numpy array 


In [2]:
import numpy as np
#Approach 1
cost_list=[10,20,30,40]
print("Selling List",cost_list*2)
cost_arr=np.array([10,20,30,40])
print("Selling Arr",cost_arr*2)
#Approach 2
d1_list=[10,20,30,40]
d2_list=[20,15,45,50]
print("Total sale",d1_list+d2_list) #Not possible
d1_Arr=np.array([10,20,30,40])
d2_Arr=np.array([20,15,45,50])
print("Total sale",d1_Arr+d2_Arr)

Selling List [10, 20, 30, 40, 10, 20, 30, 40]
Selling Arr [20 40 60 80]
Total sale [10, 20, 30, 40, 20, 15, 45, 50]
Total sale [30 35 75 90]


In [8]:

import time as t
import numpy as np
#list
start=t.time()
list_time=[i*2 for i in range(1000000)]
end=t.time()
print("list opration:",end-start)
#numpy array
start=t.time()
arr_time=np.arange(1000000)*2
end=t.time()
print("Array operation:",end-start)

list opration: 0.0870969295501709
Array operation: 0.007722139358520508


creatin array from scratch


In [14]:
#zeros
zeros=np.zeros((2,3))
print("zero matrix:\n",zeros)
#ones
ones=np.ones((3,2))
print("ones matrix:\n",ones)
#full
full=np.full((3,3),7)
print("full with num matrix:\n",full)
#random
random=np.random.random((2,2))
print("random matrix:\n",random)
#sequence,start,stop
seq=np.arange(10,31,2)
print("sequence of 10 to 30:",seq)


zero matrix:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones matrix:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
full with num matrix:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
random matrix:
 [[0.36543062 0.14987772]
 [0.66555422 0.7073527 ]]
sequence of 10 to 30: [10 12 14 16 18 20 22 24 26 28 30]


vector,matrix and tensor

In [ ]:
vector=np.array([10,20,30,40])
print("vector:\n",vector)
matrix=np.array([[10,20,30],
                [40,50,60]])
print("matrix:\n",matrix)
tensor=np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
print("tensor:\n",tensor)

vector:
 [10 20 30 40]
matrix:
 [[10 20 30]
 [40 50 60]]
tensor:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


array properties 


In [20]:
arr=np.array([[1,2,3],
              [4,5,6]])
print("shape:",arr.shape)
print("dimension:",arr.ndim)
print("size:",arr.size)
print("datatype:",arr.dtype)

shape: (2, 3)
dimension: 2
size: 6
datatype: int64


array reshaping 


In [23]:
arr=np.array(12)
print("array:",arr)
reshape=arr.reshape((4,3))
print(reshape)
mat=np.array([[10,20,30],
              [40,50,60]])
f1=mat.flatten()
print(f1)

array: 12


ValueError: cannot reshape array of size 1 into shape (4,3)