In [2]:
import numpy as np

### Aggregrate function


In [7]:
arr=np.array([10,20,30,40,50])
print("sum:",np.sum(arr))
print("max:",np.max(arr))
print("min:",np.min(arr))
print("count:",arr.size)
print("cumullative sum:",np.cumsum(arr))
print("cumullative product:",np.cumprod(arr))

sum: 150
max: 50
min: 10
count: 5
cumullative sum: [ 10  30  60 100 150]
cumullative product: [      10      200     6000   240000 12000000]


### Statistical Function

In [17]:
import statistics as st

sales=np.array([200,180,150,250,270,300,250,230,500,1000])
print("mean:",np.mean(sales))
print("median:",np.median(sales))
print("mode:",st.mode(sales))
print("Standard deviation:",np.std(sales))

mean: 333.0
median: 250.0
mode: 250
Standard deviation: 240.16869071550522


In [18]:
price=np.array([120,180,200,210,220,300])
sales=np.array([120,180,200,210,220,300])

In [3]:
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

# find the sales of data
# print sample data for first three restaurent
# Total sale per year
# Maximum sales per a student
# Maximum sales every year
# Average sales of every restaurant
# Average cummulative sales occurs all the restaurant
# Monthly Average for all the restaurant every year

In [5]:
sales = sales_data[:, 1:]
print(sales)


[[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]
 [180000 210000 240000 270000]
 [160000 185000 205000 230000]]


In [6]:
print(sales_data[:3])

[[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]


In [7]:
total_year = np.sum(sales, axis=0)
print(total_year)

[ 810000  945000 1085000 1240000]


In [8]:
max_restaurant = np.max(sales, axis=1)
print(max_restaurant)

[250000 190000 300000 270000 230000]


In [9]:
max_year = np.max(sales, axis=0)
print(max_year)

[200000 230000 260000 300000]


In [10]:
avg_restaurant = np.mean(sales, axis=1)
print(avg_restaurant)

[200000. 152500. 247500. 225000. 195000.]


In [11]:
avg_all = np.mean(sales)
print(avg_all)

204000.0


In [12]:
monthly_avg = sales / 12
print(monthly_avg)

[[12500.         15000.         18333.33333333 20833.33333333]
 [10000.         11666.66666667 13333.33333333 15833.33333333]
 [16666.66666667 19166.66666667 21666.66666667 25000.        ]
 [15000.         17500.         20000.         22500.        ]
 [13333.33333333 15416.66666667 17083.33333333 19166.66666667]]
