### Numpy Array Operations

In [1]:
import numpy as np

In [4]:
arr=np.array([10,20,30,40,50])
print("Basic Slicing:",arr[:4])
print("Slicing with step:",arr[0:5:2])
print("Negetive Index:",arr[-1])

Basic Slicing: [10 20 30 40]
Slicing with step: [10 30 50]
Negetive Index: 50


In [27]:
arr_2d=np.array([[1,2,3,10],
                 [4,5,6,20],
                 [7,8,9,30]])
print("Specific element:",arr_2d[1,2])
# print("Entire row:",arr_2d[1:,1:])  
# print("Entire column",arr_2d[0:,1]) 
print(arr_2d[2,:2])  


Specific element: 6
[7 8]


# Sorting

In [ ]:
arr_1d=np.array([3,5,2,9,5,6,1,7])
print("Sorting 1d array",sorted(arr_1d))
print("Sorting 1d array",np.sort(arr_1d))

arr_2d=np.array([[2,1],
                 [3,2],
                 [1,3]])
print("Sorting 2d array\n",np.sort(arr_2d,axis=1)) #sort the row
print("Sorting 2d array\n",np.sort(arr_2d,axis=0)) #sort the column


Sorting 1d array [np.int64(1), np.int64(2), np.int64(3), np.int64(5), np.int64(5), np.int64(6), np.int64(7), np.int64(9)]
Sorting 1d array [1 2 3 5 5 6 7 9]
Sorting 2d array
 [[1 2]
 [2 3]
 [1 3]]
Sorting 2d array
 [[1 1]
 [2 2]
 [3 3]]


## Filter

In [ ]:
number=np.array([3,5,2,9,5,6,1,7])
even_number=number[number%2==0]
print(even_number)

[2 6]


## Filter with mask

In [38]:
arr = np.array([10, 20, 30, 40, 50])
mask=arr>45
print(arr[mask])

[50]


### Index

In [40]:
arr = np.array([10, 20, 30, 40, 50])
idx = [0, 2, 4] 
print(arr[idx]) 


[10 30 50]


In [2]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([10,20,30,40])
combined=np.concatenate([arr1,arr2])
print("Combined:",combined)

Combined: [ 1  2  3  4 10 20 30 40]


In [4]:
matrix=np.array([[10,20],
                [30,40]])
newMatrix=np.array([[50,60],
                    [70,80]])
print("join Horizontal:\n",np.hstack([matrix,newMatrix]))
print("join vertically:\n",np.vstack([matrix,newMatrix]))

join Horizontal:
 [[10 20 50 60]
 [30 40 70 80]]
join vertically:
 [[10 20]
 [30 40]
 [50 60]
 [70 80]]


### Adding and Removing

In [11]:
arr=np.array([1,2,3,4,5,6])
print("split:",np.split(arr,2))
print("Append:",np.append(arr,50))
print("Insert:",np.insert(arr,0,90))
print("Remove:",np.delete(arr,2))
print("Org:",arr)


split: [array([1, 2, 3]), array([4, 5, 6])]
Append: [ 1  2  3  4  5  6 50]
Insert: [90  1  2  3  4  5  6]
Remove: [1 2 4 5 6]
Org: [1 2 3 4 5 6]
