Numpy array and basics

In [1]:
import numpy as np

Array Creation

In [11]:
#1d Array creation
arr_id=np.array([1,2,3])
# print(arr_id,type(arr_id))

#2d Array
arr_2d=np.array([[1,2,3,4,5.8],[6,7,8,9,10]])
print(arr_2d)

[[ 1.   2.   3.   4.   5.8]
 [ 6.   7.   8.   9.  10. ]]


Numpy vs list

In [18]:
list1=[10,20,30,40,50]
list_squares = [x * 2 for x in list1]
print(list_squares)

arr1=np.array([10,20,30,40,50])
numpy_squares = arr1 * 2
print(numpy_squares)

l1=[1,2,3]
l2=[5,6,7]
print(l1+l2)


ar1=np.array([1,2,3])
ar2=np.array([5,6,7])
print(ar1+ar2)

[20, 40, 60, 80, 100]
[ 20  40  60  80 100]
[1, 2, 3, 5, 6, 7]
[ 6  8 10]


In [ ]:
import time as t
import numpy as np

#List
start=t.time()
list_time=[i*2 for i in range(1000000)]
end=t.time()
print("List operation:",end-start)

#Numpy
start=t.time()
arr_time=np.arange(1000000)*2
end=t.time()
print("Array operation:",end-start)

List operation: 0.18101716041564941
Array operation: 0.008198261260986328


### Creating Array from scratch

In [25]:
#zeros
zeros=np.zeros((2,3))
# print(zeros)

#ones
ones=np.ones((3,3))
# print(ones)

#full
full=np.full((2, 2), 7)
# print(full)

#eye
eye=np.eye(3) 
# print(eye)

#Random
random=np.random.random((2,2))
# print(random)

#sequence
seq=np.arange(1,10,2)
print(seq)


[1 3 5 7 9]


### Vector, Matrix,and Tensor

In [34]:
vector=np.array([10,20,30,40])
print("Vector:\n",vector)

matrix=np.array([[10,20,30],
                [40,50,60]])
print("Matrix:\n",matrix)

tensor=np.array([[10,20,30],[40,50,60],
                [1,2,3],[4,5,6]])
print("Tensor:\n",tensor)

Vector:
 [10 20 30 40]
Matrix:
 [[10 20 30]
 [40 50 60]]
Tensor:
 [[10 20 30]
 [40 50 60]
 [ 1  2  3]
 [ 4  5  6]]


### Array Propeties

In [40]:
arr = np.array([[10, 20, 30], [40, 50, 60]])
print("Shape:", arr.shape) 
print("Dimension:",arr.ndim)
print("Size:", arr.size) 
print("Data type:", arr.dtype)

Shape: (2, 3)
Dimension: 2
Size: 6
Data type: int64


### Array Reshaping

In [ ]:
arr = np.arange(12)
print("array:",arr)
reshaped = arr.reshape((4,3)) 
print(reshaped)



array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
arr1=np.array([[1,2,3],[4,5,6]])
flattened = arr1.flatten()
print("Flattended:\n",flattened)

Flattended:
 [1 2 3 4 5 6]
